<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FleetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('fleets')->insert([
            [
                'id' => 1,
                'type' => 'C208',
                'manufacturer' => 'Cessna',
                'name' => 'Grand Caravan',
                'powerplants' => 'Pratt & Whitney',
                'number_of_engines' => 1,
                'crew_required' => 1,
                'cabin_crew_required' => 0,
                'fuel_type' => 2,
                'zfw' => 5310,
                'mtow' => 8808,
                'cargo_capacity' => 3190,
                'pax_capacity' => 10,
                'fuel_capacity' => 335,
                'fuel_consumption' => null,
                'service_ceiling' => 25000,
                'range' => 1200,
                'cruise_speed' => 174,
                'image_url' => '',
                'size' => 'M',
                'company_fleet' => 1,
                'rental_cost' => 1500.00,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 2,
                'type' => 'C172',
                'manufacturer' => 'Cessna',
                'name' => '172',
                'powerplants' => 'Lycoming',
                'number_of_engines' => 1,
                'crew_required' => 1,
                'cabin_crew_required' => 0,
                'fuel_type' => 1,
                'zfw' => 1680,
                'mtow' => 2500,
                'cargo_capacity' => 870,
                'pax_capacity' => 3,
                'fuel_capacity' => 53,
                'fuel_consumption' => null,
                'service_ceiling' => 14000,
                'range' => 640,
                'cruise_speed' => 124,
                'image_url' => '',
                'size' => 'S',
                'company_fleet' => 1,
                'rental_cost' => 170.00,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 3,
                'type' => 'B350',
                'manufacturer' => 'Beechcraft',
                'name' => 'King Air 350i',
                'powerplants' => 'Pratt & Whitney',
                'number_of_engines' => 2,
                'crew_required' => 1,
                'cabin_crew_required' => 0,
                'fuel_type' => 2, //Jet fuel
                'zfw' => 9955,
                'mtow' => 15000,
                'cargo_capacity' => 5145,
                'pax_capacity' => 10,
                'fuel_capacity' => 130,
                'fuel_consumption' => null,
                'service_ceiling' => 35000,
                'range' => 1806,
                'cruise_speed' => 312,
                'image_url' => '',
                'size' => 'L',
                'company_fleet' => 1,
                'rental_cost' => 1500.00,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 4,
                'type' => 'BN2A',
                'manufacturer' => 'Britten-Norman',
                'name' => 'BN-2 Islander',
                'powerplants' => 'Rolls Royce',
                'number_of_engines' => 2,
                'crew_required' => 1,
                'cabin_crew_required' => 0,
                'fuel_type' => 2,
                'zfw' => 3762,
                'mtow' => 6600,
                'cargo_capacity' => 5145,
                'pax_capacity' => 10,
                'fuel_capacity' => 130,
                'fuel_consumption' => null,
                'service_ceiling' => 25000,
                'range' => 728,
                'cruise_speed' => 170,
                'image_url' => '',
                'size' => 'L',
                'company_fleet' => 1,
                'rental_cost' => 1200.00,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 5,
                'type' => 'CC19',
                'manufacturer' => 'Cub Crafters',
                'name' => 'XCub',
                'powerplants' => 'Lycoming',
                'number_of_engines' => 1,
                'crew_required' => 1,
                'cabin_crew_required' => 0,
                'fuel_type' => 1,
                'zfw' => 1216,
                'mtow' => 2300,
                'cargo_capacity' => 1084,
                'pax_capacity' => 1,
                'fuel_capacity' => 49,
                'fuel_consumption' => null,
                'service_ceiling' => 15000,
                'range' => 800,
                'cruise_speed' => 130,
                'image_url' => '',
                'size' => 'S',
                'company_fleet' => 1,
                'rental_cost' => 200.00,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 6,
                'type' => 'PC6T',
                'manufacturer' => 'Pilatus',
                'name' => 'Porter PC-6',
                'powerplants' => 'Pratt & Whitney',
                'number_of_engines' => 1,
                'crew_required' => 1,
                'cabin_crew_required' => 0,
                'fuel_type' => 2,
                'zfw' => 3075,
                'mtow' => 6137,
                'cargo_capacity' => 2093,
                'pax_capacity' => 10,
                'fuel_capacity' => 298,
                'fuel_consumption' => null,
                'service_ceiling' => 26500,
                'range' => 870,
                'cruise_speed' => 115,
                'image_url' => '',
                'size' => 'M',
                'company_fleet' => 1,
                'rental_cost' => 1000.00,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 7,
                'type' => 'H135',
                'manufacturer' => 'Airbus',
                'name' => 'H135',
                'powerplants' => 'Pratt & Whitney',
                'number_of_engines' => 2,
                'crew_required' => 1,
                'cabin_crew_required' => 0,
                'fuel_type' => 2,
                'zfw' => 3681,
                'mtow' => 6834,
                'cargo_capacity' => 2250,
                'pax_capacity' => 6,
                'fuel_capacity' => 244,
                'fuel_consumption' => null,
                'service_ceiling' => 20000,
                'range' => 343,
                'cruise_speed' => 137,
                'image_url' => '',
                'size' => 'S',
                'company_fleet' => 1,
                'rental_cost' => 280.00,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
        ]
        ]);
    }
}
