<?php

namespace Tests\Unit\Services\Pirep;

use App\Models\Airport;
use App\Models\Contract;
use App\Models\ContractCargo;
use App\Models\FlightLog;
use App\Models\Pirep;
use App\Models\PirepCargo;
use App\Services\Pireps\CalculateTotalFlightDistance;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class CalcTotalFlightDistanceTest extends TestCase
{
    use RefreshDatabase;

    protected CalculateTotalFlightDistance $calculateTotalFlightDistance;
    protected Model $flightLog;
    protected Model $pirep;
    protected Model $pirepCargo;
    protected Model $contract;
    protected Model $airport;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->calculateTotalFlightDistance = $this->app->make(CalculateTotalFlightDistance::class);

        $this->contract = Contract::factory()->create();

        $this->pirep = Pirep::factory()->create();
        $this->pirepCargo = PirepCargo::factory()->create([
            'pirep_id' => $this->pirep->id,
            'contract_cargo_id' => $this->contract->id
        ]);

        FlightLog::factory()->create([
            'pirep_id' => $this->pirep->id,
            'lat' => -6.36263,
            'lon' => 143.23056
        ]);

        FlightLog::factory()->create([
            'pirep_id' => $this->pirep->id,
            'lat' => -6.14477,
            'lon' => 143.65752
        ]);

        Airport::factory()->create([
            'identifier' => 'AYMR',
            'lat' => -6.36188,
            'lon' => 143.23070,
        ]);
        Airport::factory()->create([
            'identifier' => 'AYMN'
        ]);

    }
    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_flight_distance_is_calculated()
    {
        $distance = $this->calculateTotalFlightDistance->execute($this->pirep);
        $this->assertEquals(28.6, $distance);
    }
}
