<?php

namespace Tests\Unit\Services\Pirep;

use App\Models\Aircraft;
use App\Models\Airport;
use App\Models\Contract;
use App\Models\ContractCargo;
use App\Models\Enums\PirepState;
use App\Models\Fleet;
use App\Models\Pirep;
use App\Models\PirepCargo;
use App\Models\User;
use App\Services\Pireps\FindInactivePireps;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class FindInactivePirepsTest extends TestCase
{
    use RefreshDatabase;

    protected Model $user;
    protected Model $pirep;
    protected Model $contract;
    protected Model $aircraft;
    protected Model $aymr, $aymn;
    protected FindInactivePireps $findInactivePireps;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->findInactivePireps = $this->app->make(FindInactivePireps::class);

        $this->aymn = Airport::factory()->create([
            'identifier' => 'AYMN',
            'lat' => -5.20708,
            'lon' => 144.78500
        ]);
        $this->aymr = Airport::factory()->create([
            'identifier' => 'AYMR',
            'lat' => -6.36188,
            'lon' => 143.23070
        ]);

        $this->user = User::factory()->create([
            'rank_id' => 1,
            'flights_time' => 299,
            'points' => 49,
            'created_at' => Carbon::now()->addYears(-2)
        ]);

        $this->aircraft = Aircraft::factory()->create([
            'fuel_onboard' => 50,
            'current_airport_id' => $this->aymr->id,
            'user_id' => $this->user->id
        ]);

        $this->contract = Contract::factory()->create([
            'contract_value' => 250.00,
            'dep_airport_id' => $this->aymr->id,
            'arr_airport_id' => $this->aymn->id,
        ]);
    }
    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_pirep_not_returned_when_created_recently()
    {
        $this->pirep = Pirep::factory()->create([
            'user_id' => $this->user->id,
            'destination_airport_id' => 'AYMN' ?? $this->contract->arr_airport_id,
            'departure_airport_id' => 'AYMR' ?? $this->contract->dep_airport_id,
            'aircraft_id' => $this->aircraft->id,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'state' => PirepState::DISPATCH
        ]);

        $pireps = $this->findInactivePireps->execute();

        $this->assertEquals(0, $pireps->count());
    }

    public function test_pirep_not_returned_when_active_flight_had_recent_update()
    {
        $this->pirep = Pirep::factory()->create([
            'user_id' => $this->user->id,
            'destination_airport_id' => 'AYMN' ?? $this->contract->arr_airport_id,
            'departure_airport_id' => 'AYMR' ?? $this->contract->dep_airport_id,
            'aircraft_id' => $this->aircraft->id,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'state' => PirepState::IN_PROGRESS
        ]);

        $pireps = $this->findInactivePireps->execute();

        $this->assertEquals(0, $pireps->count());
    }

    public function test_pirep_returned_when_active_flight_and_no_update_for_a_while()
    {
        $this->pirep = Pirep::factory()->create([
            'user_id' => $this->user->id,
            'destination_airport_id' => 'AYMN' ?? $this->contract->arr_airport_id,
            'departure_airport_id' => 'AYMR' ?? $this->contract->dep_airport_id,
            'aircraft_id' => $this->aircraft->id,
            'created_at' => Carbon::now()->subHours(5),
            'updated_at' => Carbon::now()->subHours(3),
            'state' => PirepState::IN_PROGRESS
        ]);

        $pireps = $this->findInactivePireps->execute();

        $this->assertEquals(1, $pireps->count());
    }

    public function test_pireps_will_be_removed()
    {
        $this->pirep = Pirep::factory()->create([
            'user_id' => $this->user->id,
            'destination_airport_id' => 'AYMN' ?? $this->contract->arr_airport_id,
            'departure_airport_id' => 'AYMR' ?? $this->contract->dep_airport_id,
            'aircraft_id' => $this->aircraft->id,
            'created_at' => Carbon::now()->subHours(12),
            'updated_at' => Carbon::now()->subHours(12),
            'state' => PirepState::DISPATCH
        ]);

        $pireps = $this->findInactivePireps->execute();

        $this->assertEquals(1, $pireps->count());
    }
}
