<?php

namespace Tests\Unit\Services\Pirep;

use App\Models\Aircraft;
use App\Models\Airport;
use App\Models\Contract;
use App\Models\ContractCargo;
use App\Models\Fleet;
use App\Models\Pirep;
use App\Models\PirepCargo;
use App\Models\User;
use App\Services\Pireps\RemoveSinglePirep;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class RemovePirepTest extends TestCase
{
    use RefreshDatabase;

    protected Model $user;
    protected Model $pirep;
    protected Model $pirepCargo;
    protected Model $contract;
    protected Model $fleet;
    protected Model $aircraft;
    protected Model $booking;
    protected RemoveSinglePirep $removeSinglePirep;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->removeSinglePirep = $this->app->make(RemoveSinglePirep::class);

        $this->user = User::factory()->create([
            'rank_id' => 1,
            'flights_time' => 299,
            'points' => 49,
            'created_at' => Carbon::now()->addYears(-2)
        ]);

        $aymr = Airport::factory()->create([
            'identifier' => 'AYMR',
            'lat' => -6.36188,
            'lon' => 143.23070
        ]);
        $aymn = Airport::factory()->create([
            'identifier' => 'AYMN',
            'lat' => -5.20708,
            'lon' => 144.78500
        ]);

        $this->aircraft = Aircraft::factory()->create([
            'fuel_onboard' => 50,
            'current_airport_id' => $aymr->id,
            'user_id' => $this->user->id
        ]);
        DB::table('cargo_types')->insert([
            ['type' => 1, 'text' => 'Solar Panels'],
            ['type' => 1, 'text' => 'Building materials'],
            ['type' => 2, 'text' => 'Medics'],
            ['type' => 2, 'text' => 'Locals'],
        ]);

        $this->contract = Contract::factory()->create([
            'contract_value' => 250.00,
            'dep_airport_id' => $aymr->id,
            'arr_airport_id' => $aymn->id,
            'current_airport_id' => $aymr->id,
        ]);

        $this->pirep = Pirep::factory()->create([
            'user_id' => $this->user->id,
            'destination_airport_id' => 'AYMR' ?? $this->contract->arr_airport_id,
            'departure_airport_id' => 'AYMR' ?? $this->contract->dep_airport_id,
            'aircraft_id' => $this->aircraft
        ]);

        $this->pirepCargo = PirepCargo::factory()->create([
            'pirep_id' => $this->pirep->id,
            'contract_cargo_id' => $this->contract->id
        ]);
    }
    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_pirep_is_removed()
    {
        $this->removeSinglePirep->execute($this->pirep);
        $this->assertDatabaseMissing('pireps', ['id' => $this->pirep->id]);
    }

    public function test_pirep_cargo_is_removed()
    {
        $this->removeSinglePirep->execute($this->pirep);
        $this->assertDatabaseMissing('pirep_cargos', ['pirep_id' => $this->pirep->id]);
    }

    public function test_contract_cargo_reset()
    {
        $this->removeSinglePirep->execute($this->pirep);
        $this->assertDatabaseHas('contracts', [
            'id' => $this->contract->id,
            'is_available' => 1,
            'user_id' => null
        ]);
    }
}
