<?php

namespace Tests\Unit\Services\Pirep;

use App\Models\Aircraft;
use App\Models\Booking;
use App\Models\Fleet;
use App\Models\Flight;
use App\Models\Pirep;
use App\Models\User;
use App\Services\PirepService;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Artisan;
use Tests\TestCase;

class SetPirepScoreTest extends TestCase
{
    use RefreshDatabase;

    protected Model $user;
    protected Model $pirep;
    protected Model $flight;
    protected Model $booking;
    protected Model $fleet;
    protected Model $aircraft;
    protected PirepService $pirepService;

    protected function setUp(): void
    {

        parent::setUp(); // TODO: Change the autogenerated stub
        Artisan::call('db:seed --class=RankSeeder');
        $this->pirepService = new PirepService();
        $this->user = User::factory()->create([
            'rank_id' => 1
        ]);
        $this->fleet = Fleet::factory()->create();
        $this->aircraft = Aircraft::factory()->create([
            'fleet_id' => $this->fleet->id
        ]);
        $this->flight = Flight::factory()->create([
            'dep_airport_id' => 'EGLL',
            'arr_airport_id' => 'LFPG'
        ]);
        $this->booking = Booking::factory()->create([
            'user_id' => $this->user->id,
            'flight_id' => $this->flight->id,
        ]);
        $this->pirep = Pirep::factory()->create([
            'user_id' => $this->user->id,
            'flight_id' => $this->flight->id,
            'aircraft_id' => $this->aircraft->id,
            'booking_id' => $this->booking->id,
            'landing_rate' => 150,
            'distance' => 50,
            'flight_time' => 60
        ]);
    }
    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_pirep_score_calculates()
    {
        $this->pirepService->calculatePoints($this->pirep);
        $this->pirepService->updatePirepTotalScore($this->pirep);

        $this->assertDatabaseHas('pireps', [
            'id' => $this->pirep->id,
            'score' => 107
        ]);
    }
}
