<?php

namespace Tests\Unit\Rentals;

use App\Models\Aircraft;
use App\Models\Airport;
use App\Models\Enums\TransactionTypes;
use App\Models\Fleet;
use App\Models\Rental;
use App\Models\User;
use App\Services\Rentals\EndRental;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class EndRentalTest extends TestCase
{
    use RefreshDatabase;

    protected Model $fleet;
    protected Model $aircraftHome;
    protected Model $aircraftAway;
    protected Model $user;
    protected EndRental $endRental;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->fleet = Fleet::factory()->create([
            'rental_cost' => 200.00
        ]);

        $this->user = User::factory()->create();

        $aymr = Airport::factory()->create([
            'identifier' => 'AYMR',
            'is_hub' => true
        ]);
        $aymh = Airport::factory()->create([
            'identifier' => 'AYMH'
        ]);

        $this->aircraftHome = Rental::factory()->create([
            'fleet_id' => $this->fleet->id,
            'current_airport_id' => $aymr->id,
            'rental_airport_id' => $aymr->id,
            'user_id' => $this->user->id,
            'registration' => 'N12345'
        ]);

        $this->aircraftAway = Rental::factory()->create([
            'fleet_id' => $this->fleet->id,
            'current_airport_id' => $aymh->id,
            'rental_airport_id' => $aymr->id,
            'user_id' => $this->user->id,
            'registration' => 'N1234A'
        ]);

        $this->endRental = $this->app->make(EndRental::class);
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_rental_made_inactive()
    {
        $this->endRental->execute($this->aircraftHome->id, $this->user->id);
        $this->aircraftHome->refresh();
        $this->assertEquals(0, $this->aircraftHome->is_active);
    }
}
