<?php

namespace Tests\Feature\Api\Contracts;

use App\Models\Contract;
use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class AssignContractTest extends TestCase
{
    use RefreshDatabase;
    protected Model $contract;
    protected Model $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->contract = Contract::factory()->create();
        $this->user = User::factory()->create();
    }
    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_returns_success_response()
    {
        $response = $this->postJson('/api/contracts/assign', ['id' => $this->contract->id, 'action' => 'assign', 'userId' => $this->user->id]);
        $response->assertStatus(200);
    }

    public function test_contract_assigned()
    {
        $response = $this->postJson('/api/contracts/assign', ['id' => $this->contract->id, 'action' => 'assign', 'userId' => $this->user->id]);
        $this->contract->refresh();
        $this->assertEquals($this->user->id, $this->contract->user_id);
    }

    public function test_contract_made_unavailable()
    {
        $response = $this->postJson('/api/contracts/assign', ['id' => $this->contract->id, 'action' => 'cancel']);
        $this->contract->refresh();
        $this->assertEquals(null, $this->contract->user_id);
    }
}
