<?php

namespace Tests\Feature\Api\Contracts;

use App\Models\Airport;
use App\Models\Contract;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class BidForContractTest extends TestCase
{
    use RefreshDatabase;
    protected Contract $contract;
    protected Airport $arrAirport;
    protected Airport $depAirport;
    protected User $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::factory()->create();

        $this->depAirport = Airport::factory()->create([
            'identifier' => 'AYMR',
            'lat' => -6.36188,
            'lon' => 143.23070,
            'is_hub' => false
        ]);
        $this->arrAirport = Airport::factory()->create([
            'identifier' => 'AYMN',
            'lat' => -6.14617,
            'lon' => 143.65733,
            'is_hub' => false
        ]);

        $this->contract = Contract::factory()->create([
            'arr_airport_id' => $this->arrAirport->id,
            'dep_airport_id' => $this->depAirport->id,
        ]);

    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_returns_success_response(): void
    {
        $response = $this->postJson('/api/contracts/bid', ['id' => $this->contract->id, 'userId' => $this->user->id]);
        $response->assertStatus(200);
    }

    public function test_contract_made_unavailable(): void
    {
        $this->contract->refresh();
        $this->assertEquals(true, $this->contract->is_available);
        $this->postJson('/api/contracts/bid', ['id' => $this->contract->id, 'userId' => $this->user->id]);
        $this->contract->refresh();
        $this->assertEquals(false, $this->contract->is_available);
    }

    public function test_returns_not_found_response_when_invalid(): void
    {
        $response = $this->postJson('/api/contracts/bid', ['id' => 2, 'userId' => $this->user->id]);
        $response->assertStatus(404);
    }

    public function test_fuel_contract_returns_fuel_to_airport(): void
    {
        $airport = Airport::factory()->create([
            'identifier' => 'WAZO',
            'avgas_qty' => 10,
            'is_hub' => false
        ]);
        $contract = Contract::factory()->create([
            'dep_airport_id' => $airport->id,
            'is_fuel' => true,
            'fuel_qty' => 100,
            'fuel_type' => 1
        ]);
        $this->postJson('/api/contracts/bid', ['id' => $contract->id, 'action' => 'remove',  'userId' => $this->user->id]);
        $airport->refresh();
        $this->assertEquals(110, $airport->avgas_qty);
    }

    public function test_fuel_contract_is_removed(): void
    {
        $contract = Contract::factory()->create([
            'dep_airport_id' => $this->arrAirport->id,
            'is_fuel' => true,
            'fuel_qty' => 100,
            'fuel_type' => 1
        ]);
        $this->postJson('/api/contracts/bid', ['id' => $contract->id, 'action' => 'remove', 'userId' => $this->user->id]);
        $this->assertDatabaseMissing('contracts', [
            'id' => $contract->id
        ]);
    }
}
