<?php

namespace Tests\Feature\Api\Contracts;

use App\Models\Contract;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class BidForContractTest extends TestCase
{
    use RefreshDatabase;
    protected Model $contract;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->contract = Contract::factory()->create();
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_returns_success_response()
    {
        $response = $this->postJson('/api/contracts/bid', ['id' => $this->contract->id]);
        $response->assertStatus(201);
    }

    public function test_contract_made_unavailable()
    {
        $this->postJson('/api/contracts/bid', ['id' => $this->contract->id]);
        $this->contract->refresh();
        $this->assertEquals(false, $this->contract->is_available);
    }

    public function test_returns_not_found_response_when_invalid()
    {
        $response = $this->postJson('/api/contracts/bid', ['id' => 2]);
        $response->assertStatus(404);
    }
}
