<?php

namespace Tests\Unit\Models;

use App\Models\Airport;
use App\Models\Enums\FuelType;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class AirportFuelTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * A basic unit test example.
     */
    public function test_hub_qty_does_not_change(): void
    {
        $airport = Airport::factory()->create([
            'is_hub' => true,
            'avgas_qty' => null
        ]);
        $airport->adjustFuel(FuelType::AVGAS, 10);
        $airport->refresh();
        $this->assertNull($airport->avgas_qty);
    }

    public function test_avgas_decreases(): void
    {
        $airport = Airport::factory()->create([
            'is_hub' => false,
            'avgas_qty' => 100
        ]);
        $airport->adjustFuel(1, -10);
        $airport->refresh();
        $this->assertEquals(90, $airport->avgas_qty);
    }

    public function test_avgas_increase(): void
    {
        $airport = Airport::factory()->create([
            'is_hub' => false,
            'avgas_qty' => 100
        ]);
        $airport->adjustFuel(1, 10);
        $airport->refresh();
        $this->assertEquals(110, $airport->avgas_qty);
    }

    public function test_jetfuel_decreases(): void
    {
        $airport = Airport::factory()->create([
            'is_hub' => false,
            'jetfuel_qty' => 100
        ]);
        $airport->adjustFuel(2, -10);
        $airport->refresh();
        $this->assertEquals(90, $airport->jetfuel_qty);
    }

    public function test_jetfuel_increase(): void
    {
        $airport = Airport::factory()->create([
            'is_hub' => false,
            'jetfuel_qty' => 100
        ]);
        $airport->adjustFuel(2, 10);
        $airport->refresh();
        $this->assertEquals(110, $airport->jetfuel_qty);
    }
}
