<?php

namespace Tests\Unit\Models;

use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class UserTest extends TestCase
{
    use RefreshDatabase;
    protected Model $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::factory()->create();
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_private_name_attribute()
    {
        $firstName = strstr($this->user->name, ' ', true);
        $lastName = substr($this->user->name, strpos($this->user->name, ' ') + 1);
        $expected = $firstName.' '.$lastName[0];
        $this->assertEquals($expected, $this->user->getPrivateNameAttribute());
    }

    public function test_pilot_id_attribute()
    {
        $expected = str_pad($this->user->id, 4, "0", STR_PAD_LEFT);
        $this->assertEquals('BDV'.$expected, $this->user->getPilotIdAttribute());
    }

}
