<?php

namespace Tests\Unit\Services\Financial;

use App\Models\Aircraft;
use App\Models\AirlineFees;
use App\Models\Airport;
use App\Models\Contract;
use App\Models\ContractCargo;
use App\Models\Enums\AirlineTransactionTypes;
use App\Models\Enums\TransactionTypes;
use App\Models\Fleet;
use App\Models\Pirep;
use App\Models\PirepCargo;
use App\Models\Rental;
use App\Models\User;
use App\Services\Finance\CalcCargoHandlingFee;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class CargoHandlingFeeTest extends TestCase
{
    use RefreshDatabase;

    protected CalcCargoHandlingFee $calcCargoHandlingFee;
    protected Model $contract;
    protected Model $contractCargo;
    protected Model $pirep;
    protected Model $pirepCargo;
    protected Model $fleet;
    protected Model $airport;
    protected Model $aircraft;
    protected Model $aircraftRental;
    protected Model $aircraftPrivate;
    protected Model $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->calcCargoHandlingFee = $this->app->make(CalcCargoHandlingFee::class);
        $this->contract = Contract::factory()->create();
        $this->contractCargo = ContractCargo::factory()->create([
            'contract_id' => $this->contract->id
        ]);
        $this->airport = Airport::factory()->create([
            'size' => 1
        ]);

        $this->user = User::factory()->create();

        AirlineFees::factory()->create([
            'fee_type' => AirlineTransactionTypes::GroundHandlingFees,
            'fee_name' => 'Cargo Handling',
            'fee_weight' => 1,
            'fee_amount' => 0.15
        ]);
        $this->fleet = Fleet::factory()->create();
        $this->aircraft = Aircraft::factory()->create([
            'fleet_id' => $this->fleet->id
        ]);

        $this->aircraftRental = Rental::factory()->create([
            'fleet_id' => $this->fleet->id,
            'user_id' => $this->user->id,
            'registration' => 'N12345'
        ]);

        $this->aircraftPrivate = Aircraft::factory()->create([
            'fleet_id' => $this->fleet->id,
            'owner_id' => 1,
            'registration' => 'N12345P'
        ]);

        $this->pirep = Pirep::factory()->create([
            'destination_airport_id' => $this->airport->identifier,
            'aircraft_id' => $this->aircraft
        ]);
        $this->pirepCargo = PirepCargo::factory()->create([
            'pirep_id' => $this->pirep->id,
            'contract_cargo_id' => $this->contractCargo->id
        ]);

    }
    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_cargo_calculated()
    {
        $cost = $this->contractCargo->cargo_qty * 0.15;
        $this->calcCargoHandlingFee->execute($this->pirep);
        $this->assertDatabaseHas('account_ledgers', [
            'memo' => 'Cargo Handling',
            'pirep_id' => $this->pirep->id,
            'total' => -$cost,
            'transaction_type' => AirlineTransactionTypes::GroundHandlingFees
        ]);
    }

    public function test_cargo_calculated_for_rental()
    {
        $pirep = Pirep::factory()->create([
            'destination_airport_id' => $this->airport->identifier,
            'aircraft_id' => $this->aircraftRental->id,
            'is_rental' => true
        ]);
        PirepCargo::factory()->create([
            'pirep_id' => $pirep->id,
            'contract_cargo_id' => $this->contractCargo->id
        ]);

        $cost = $this->contractCargo->cargo_qty * 0.15;
        $this->calcCargoHandlingFee->execute($pirep);
        $this->assertDatabaseMissing('account_ledgers', [
            'pirep_id' => $pirep->id,
        ]);
        $this->assertDatabaseHas('user_accounts', [
            'flight_id' => $pirep->id,
            'total' => -$cost,
            'type' => TransactionTypes::FlightFeesGround
        ]);
    }

    public function test_cargo_calculated_for_private()
    {
        $pirep = Pirep::factory()->create([
            'destination_airport_id' => $this->airport->identifier,
            'aircraft_id' => $this->aircraftPrivate->id
        ]);
        PirepCargo::factory()->create([
            'pirep_id' => $pirep->id,
            'contract_cargo_id' => $this->contractCargo->id
        ]);

        $cost = $this->contractCargo->cargo_qty * 0.15;
        $this->calcCargoHandlingFee->execute($pirep);
        $this->assertDatabaseMissing('account_ledgers', [
            'pirep_id' => $pirep->id,
        ]);
        $this->assertDatabaseHas('user_accounts', [
            'flight_id' => $pirep->id,
            'total' => -$cost,
            'type' => TransactionTypes::FlightFeesGround
        ]);
    }

    public function test_cargo_not_calculated_for_small_airport()
    {
        $airport = Airport::factory()->create([
            'size' => 1
        ]);
        $pirep = Pirep::factory()->create([
            'destination_airport_id' => $airport->identifier
        ]);
        $pirepCargo = PirepCargo::factory()->create([
            'pirep_id' => $pirep->id,
            'contract_cargo_id' => $this->contractCargo->id
        ]);

        $this->calcCargoHandlingFee->execute($pirep);
        $this->assertDatabaseMissing('account_ledgers', [
            'memo' => 'Cargo Handling',
            'pirep_id' => $this->pirep->id,
            'transaction_type' => AirlineTransactionTypes::GroundHandlingFees
        ]);
    }
}
