<?php

namespace Tests\Unit\Services\Financial;

use App\Models\Aircraft;
use App\Models\AirlineFees;
use App\Models\Airport;
use App\Models\Contract;
use App\Models\ContractCargo;
use App\Models\Enums\AirlineTransactionTypes;
use App\Models\Enums\TransactionTypes;
use App\Models\Fleet;
use App\Models\Pirep;
use App\Models\PirepCargo;
use App\Models\Rental;
use App\Models\User;
use App\Services\Finance\CalcLandingFee;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class LandingFeeTest extends TestCase
{
    use RefreshDatabase;

    protected CalcLandingFee $calcLandingFee;
    protected Model $pirep;
    protected Model $fleetSmall;
    protected Model $fleetMedium;
    protected Model $fleetLarge;
    protected Model $aircraftSmall;
    protected Model $aircraftMedium;
    protected Model $aircraftLarge;
    protected Model $airport;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->calcLandingFee = $this->app->make(CalcLandingFee::class);
        $this->airport = Airport::factory()->create([
            'size' => 1
        ]);
        $this->fleetSmall = Fleet::factory()->create(['size' => 'S', 'type' => 'C172']);
        $this->fleetMedium = Fleet::factory()->create(['size' => 'M', 'type' => 'C208']);
        $this->fleetLarge = Fleet::factory()->create(['size' => 'L', 'type' => 'TBM9']);
        $this->aircraftSmall = Aircraft::factory()->create([
            'registration' => 'P2-SM',
            'fleet_id' => $this->fleetSmall->id
        ]);
        $this->aircraftMedium = Aircraft::factory()->create([
            'registration' => 'P2-MD',
            'fleet_id' => $this->fleetMedium->id
        ]);
        $this->aircraftLarge = Aircraft::factory()->create([
            'registration' => 'P2-LG',
            'fleet_id' => $this->fleetLarge->id
        ]);

        AirlineFees::factory()->create([
            'fee_type' => AirlineTransactionTypes::LandingFees,
            'fee_name' => 'Landing Fees - Small',
            'fee_amount' => 35.00
        ]);
        AirlineFees::factory()->create([
            'fee_type' => AirlineTransactionTypes::LandingFees,
            'fee_name' => 'Landing Fees - Medium',
            'fee_amount' => 100.00
        ]);
        AirlineFees::factory()->create([
            'fee_type' => AirlineTransactionTypes::LandingFees,
            'fee_name' => 'Landing Fees - Large',
            'fee_amount' => 250.00
        ]);
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_small_landing_fee_calculated()
    {
        $pirep = Pirep::factory()->create([
            'aircraft_id' => $this->aircraftSmall->id,
            'destination_airport_id' => $this->airport->identifier
        ]);
        $this->calcLandingFee->execute($pirep);
        $this->assertDatabaseHas('account_ledgers', [
            'transaction_type' => AirlineTransactionTypes::LandingFees,
            'memo' => 'Landing Fees - Small',
            'pirep_id' => $pirep->id,
            'total' => -35
        ]);
    }

    public function test_small_landing_fee_not_calculated_rental()
    {
        $user = User::factory()->create();

        $aircraft = Rental::factory()->create([
            'fleet_id' => $this->fleetSmall->id,
            'user_id' => $user->id
        ]);

        $pirep = Pirep::factory()->create([
            'aircraft_id' => $aircraft->id,
            'destination_airport_id' => $this->airport->identifier,
            'is_rental' => true
        ]);
        $this->calcLandingFee->execute($pirep);
        $this->assertDatabaseMissing('account_ledgers', [
            'pirep_id' => $pirep->id
        ]);

        $this->assertDatabaseHas('user_accounts', [
            'type' => TransactionTypes::FlightFeesLanding,
            'flight_id' => $pirep->id,
            'total' => -35
        ]);
    }

    public function test_small_landing_fee_not_calculated_private()
    {
        $aircraft = Aircraft::factory()->create([
            'fleet_id' => $this->fleetSmall->id,
            'owner_id' => 1
        ]);

        $pirep = Pirep::factory()->create([
            'aircraft_id' => $aircraft->id,
            'destination_airport_id' => $this->airport->identifier
        ]);
        $this->calcLandingFee->execute($pirep);
        $this->assertDatabaseMissing('account_ledgers', [
            'pirep_id' => $pirep->id
        ]);

        $this->assertDatabaseHas('user_accounts', [
            'type' => TransactionTypes::FlightFeesLanding,
            'flight_id' => $pirep->id,
            'total' => -35
        ]);
    }

    public function test_medium_landing_fee_calculated()
    {
        $pirep = Pirep::factory()->create([
            'aircraft_id' => $this->aircraftMedium->id,
            'destination_airport_id' => $this->airport->identifier
        ]);
        $this->calcLandingFee->execute($pirep);
        $this->assertDatabaseHas('account_ledgers', [
            'transaction_type' => AirlineTransactionTypes::LandingFees,
            'memo' => 'Landing Fees - Medium',
            'pirep_id' => $pirep->id,
            'total' => -100
        ]);
    }

    public function test_large_landing_fee_calculated()
    {
        $pirep = Pirep::factory()->create([
            'aircraft_id' => $this->aircraftLarge->id,
            'destination_airport_id' => $this->airport->identifier
        ]);
        $this->calcLandingFee->execute($pirep);
        $this->assertDatabaseHas('account_ledgers', [
            'transaction_type' => AirlineTransactionTypes::LandingFees,
            'memo' => 'Landing Fees - Large',
            'pirep_id' => $pirep->id,
            'total' => -250
        ]);
    }

    public function test_landing_fee_not_calculated_at_small_afield()
    {
        $airport = Airport::factory()->create([
            'identifier' => 'AYMN',
            'size' => 0
        ]);

        $pirep = Pirep::factory()->create([
            'aircraft_id' => $this->aircraftLarge->id,
            'destination_airport_id' => $airport->identifier
        ]);
        $this->calcLandingFee->execute($pirep);
        $this->assertDatabaseMissing('account_ledgers', [
            'transaction_type' => AirlineTransactionTypes::LandingFees,
            'pirep_id' => $pirep->id
        ]);
    }
}
