<?php

namespace Tests\Unit\Services\Weather;

use App\Services\Airports\GetMetarForAirport;
use Illuminate\Support\Facades\Cache;
use Tests\TestCase;

class GetMetarTest extends TestCase
{
    protected GetMetarForAirport $getMetarForAirport;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->getMetarForAirport = $this->app->make(GetMetarForAirport::class);
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_returned_for_valid_icao()
    {
        $metar = $this->getMetarForAirport->execute('EGLL');
        $this->assertNotEmpty($metar);
    }

    public function test_empty_string_is_returned_for_invalid_icao()
    {
        $metar = $this->getMetarForAirport->execute('LLLL');
        $this->assertEmpty($metar);
    }
}
