<?php

namespace Tests\Feature\Api\Fleet;

use App\Models\Aircraft;
use App\Models\Airport;
use App\Models\Fleet;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class GetAvailableAircraftTest extends TestCase
{
    use RefreshDatabase;

    protected Aircraft $aircraft;
    protected Fleet $fleet;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $airport = Airport::factory()->create([
            'identifier' => 'AYMR',
            'is_hub' => true
        ]);
        $this->fleet = Fleet::factory()->create();
        $this->aircraft = Aircraft::factory()->create([
            'fleet_id' => $this->fleet->id,
            'current_airport_id' => $airport->id
        ]);

        $this->markTestSkipped('Testing removal of aircraft API');
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_aircraft_returned_ok(): void
    {
        $response = $this->getJson('/api/aircraft/'.'AYMR');

        $response->assertStatus(200);
    }

    public function test_aircraft_details_returned(): void
    {
        $response = $this->getJson('/api/aircraft/'.'AYMR');

        $response->assertJsonFragment(['id' => $this->aircraft->id]);
    }

    public function test_aircraft_details_not_available_for_icao_with_no_aircraft(): void
    {
        Airport::factory()->create([
            'identifier' => 'EGLL',
            'is_hub' => true
        ]);
        $response = $this->getJson('/api/aircraft/'.'EGLL');

        $response->assertJsonCount(0, 'aircraft');
    }
}
