<?php

namespace Tests\Feature\Contracts;

use App\Models\Contract;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class CancelContractTest extends TestCase
{
    use RefreshDatabase;
    protected Model $contract;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->contract = Contract::factory()->create();
    }
    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_can_cancel_contract()
    {
        $this->post('/contracts/cancel', ['id' => $this->contract->id]);
        $this->assertDatabaseCount('contracts', 0);
    }
}
