<?php

namespace Tests\Feature\Api\Airport;

use App\Models\Airport;
use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class GetAirportFromSearchTest extends TestCase
{
    use RefreshDatabase;

    protected Model $airport;
    protected User $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->airport = Airport::factory()->create();

        $this->user = User::factory()->create();
        $this->actingAs($this->user);
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_airport_search_is_successful()
    {
        $response = $this->getJson('api/airport/search/'.$this->airport->identifier);
        $response->assertStatus(200);
    }

    public function test_airport_search_returns_airport()
    {
        $response = $this->getJson('api/airport/search/'.$this->airport->identifier);
        $response->assertJsonFragment(['identifier' => $this->airport->identifier]);
    }

    public function test_airport_search_handled_when_no_airport_found()
    {
        $response = $this->getJson('api/airport/search/EGLL');
        $response->assertStatus(200);
    }

    public function test_airport_thirdparty_search_scopes()
    {
        $tpAirport = Airport::factory()->create([
            'is_thirdparty' => true,
            'identifier' => 'TP01'
        ]);

        $response = $this->getJson('api/airport/search/'.$tpAirport->identifier.'?base=1');
        $response->assertJsonMissing(['identifier' => $tpAirport->identifier]);

        $response = $this->getJson('api/airport/search/'.$tpAirport->identifier);
        $response->assertJsonFragment(['identifier' => $tpAirport->identifier]);
    }

    public function test_airport_thirdparty_user_preference_scope()
    {
        $tpAirport = Airport::factory()->create([
            'is_thirdparty' => true,
            'identifier' => 'TP02'
        ]);

        $tpHubAirport = Airport::factory()->hub()->create([
            'is_thirdparty' => true,
            'identifier' => 'TPHUB'
        ]);

        $this->user->allow_thirdparty_airport = false;
        $this->user->allow_thirdparty_hub = false;
        $this->user->save();

        $response = $this->getJson('api/airport/search/'.$tpAirport->identifier.'?user=1');
        $response->assertJsonMissing(['identifier' => $tpAirport->identifier]);

        $response = $this->getJson('api/airport/search/'.$tpHubAirport->identifier.'?user=1');
        $response->assertJsonMissing(['identifier' => $tpHubAirport->identifier]);

        $this->user->allow_thirdparty_hub = true;
        $this->user->save();

        $response = $this->getJson('api/airport/search/'.$tpAirport->identifier.'?user=1');
        $response->assertJsonMissing(['identifier' => $tpAirport->identifier]);

        $response = $this->getJson('api/airport/search/'.$tpHubAirport->identifier.'?user=1');
        $response->assertJsonFragment(['identifier' => $tpHubAirport->identifier]);

        $this->user->allow_thirdparty_airport = true;
        $this->user->save();

        $response = $this->getJson('api/airport/search/'.$tpAirport->identifier.'?user=1');
        $response->assertJsonFragment(['identifier' => $tpAirport->identifier]);
    }
}
