<?php

namespace Tests\Feature\Api\Airport;

use App\Models\Airport;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class GetAirportFromSearchTest extends TestCase
{
    use RefreshDatabase;

    protected Model $airport;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->airport = Airport::factory()->create();

        $user = \App\Models\User::factory()->create();
        \Laravel\Sanctum\Sanctum::actingAs(
            $user,
            ['*']
        );
    }
    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_airport_search_is_successful()
    {
        $response = $this->getJson('api/airport/search/'.$this->airport->identifier);
        $response->assertStatus(200);
    }

    public function test_airport_search_returns_airport()
    {
        $response = $this->getJson('api/airport/search/'.$this->airport->identifier);
        $response->assertJsonFragment(['identifier' => $this->airport->identifier]);
    }

    public function test_airport_search_handled_when_no_airport_found()
    {
        $response = $this->getJson('api/airport/search/EGLL');
        $response->assertStatus(200);
    }

    public function test_airport_thirdparty_search_scopes()
    {
        $tpAirport = Airport::factory()->create([
            'is_thirdparty' => true,
            'identifier' => 'TP01'
        ]);

        $response = $this->getJson('api/airport/search/'.$tpAirport->identifier.'?base=1');
        $response->assertJsonMissing(['identifier' => $tpAirport->identifier]);

        $response = $this->getJson('api/airport/search/'.$tpAirport->identifier);
        $response->assertJsonFragment(['identifier' => $tpAirport->identifier]);
    }
}
