<?php

namespace Tests\Unit\Services\Airport;

use App\Services\Airports\CalcDistanceBetweenPoints;
use Tests\TestCase;

class AirportDistanceTest extends TestCase
{
    protected CalcDistanceBetweenPoints $calcDistanceBetweenPoints;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->calcDistanceBetweenPoints = $this->app->make(CalcDistanceBetweenPoints::class);
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_short_distance_between_moro_and_MH()
    {
        $distance = $this->calcDistanceBetweenPoints->execute(-6.36188, 143.23070, -5.82781, 144.29953);
        $this->assertEquals(71.4, $distance);
    }

    public function test_mid_distance_between_moro_and_aypy()
    {
        $distance = $this->calcDistanceBetweenPoints->execute(-6.36188, 143.23070, -9.442119, 147.217545);
        $this->assertEquals(300.7, $distance);
    }

    public function test_mid_distance_between_moro_and_heathrow()
    {
        $distance = $this->calcDistanceBetweenPoints->execute(-6.36188, 143.23070, 51.472099, -0.452730);
        $this->assertEquals(7555.4, $distance);
    }
}
