<?php

namespace Tests\Unit\Services\Airport;

use App\Models\Airport;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class AirportDistanceTest extends TestCase
{
    use RefreshDatabase;

    protected Airport $moro;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->moro = Airport::factory()->create([
            'identifier' => 'AYMR',
            'name' => 'Moro Airport',
            'country' => 'PG',
            'is_hub' => false,
            'lat' => -6.36188,
            'lon' => 143.23070,
            'altitude' => 100
        ]);
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_short_distance_between_moro_and_MH(): void
    {
        /** @var Airport  */
        $mh = Airport::factory()->create([
            'identifier' => 'AYMH',
            'name' => 'Mount Hagen Airport',
            'country' => 'PG',
            'is_hub' => false,
            'lat' => -5.82781,
            'lon' => 144.29953,
            'altitude' => 100
        ]);

        $distance = $this->moro->distanceTo($mh);
        $this->assertEquals(71.4, $distance);
    }

    public function test_mid_distance_between_moro_and_aypy(): void
    {
        /** @var Airport  */
        $aypy = Airport::factory()->create([
            'identifier' => 'AYPY',
            'name' => 'Port Moresby Jacksons International Airport',
            'country' => 'PG',
            'is_hub' => true,
            'lat' => -9.442119,
            'lon' => 147.217545,
            'altitude' => 100
        ]);

        $distance = $this->moro->distanceTo($aypy);
        $this->assertEquals(300.7, $distance);
    }

    public function test_mid_distance_between_moro_and_heathrow(): void
    {
        /** @var Airport  */
        $heathrow = Airport::factory()->create([
            'identifier' => 'EGLL',
            'name' => 'Heathrow Airport',
            'country' => 'GB',
            'is_hub' => true,
            'lat' => 51.472099,
            'lon' => -0.452730,
            'altitude' => 100
        ]);

        $distance = $this->moro->distanceTo($heathrow);
        $this->assertEquals(7555.4, $distance);
    }
}
