<?php

namespace Tests\Unit\Services\Airport;

use App\Models\Airport;
use App\Services\Airports\UpdateFuelAtAirport;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class UpdateFuelAtAirportTest extends TestCase
{
    use RefreshDatabase;
    protected UpdateFuelAtAirport $updateFuelAtAirport;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->updateFuelAtAirport = $this->app->make(UpdateFuelAtAirport::class);
    }

    /**
     * A basic unit test example.
     */
    public function test_hub_qty_does_not_change(): void
    {
        $airport = Airport::factory()->create([
            'is_hub' => true,
            'avgas_qty' => null
        ]);
        $this->updateFuelAtAirport->execute($airport->identifier, 10, 1, 'decrement');
        $airport->refresh();
        $this->assertNull($airport->avgas_qty);
    }

    public function test_avgas_decreases(): void
    {
        $airport = Airport::factory()->create([
            'is_hub' => false,
            'avgas_qty' => 100
        ]);
        $this->updateFuelAtAirport->execute($airport->identifier, 10, 1, 'decrement');
        $airport->refresh();
        $this->assertEquals(90, $airport->avgas_qty);
    }

    public function test_avgas_increase(): void
    {
        $airport = Airport::factory()->create([
            'is_hub' => false,
            'avgas_qty' => 100
        ]);
        $this->updateFuelAtAirport->execute($airport->identifier, 10, 1, 'increment');
        $airport->refresh();
        $this->assertEquals(110, $airport->avgas_qty);
    }

    public function test_jetfuel_decreases(): void
    {
        $airport = Airport::factory()->create([
            'is_hub' => false,
            'jetfuel_qty' => 100
        ]);
        $this->updateFuelAtAirport->execute($airport->identifier, 10, 2, 'decrement');
        $airport->refresh();
        $this->assertEquals(90, $airport->jetfuel_qty);
    }

    public function test_jetfuel_increase(): void
    {
        $airport = Airport::factory()->create([
            'is_hub' => false,
            'jetfuel_qty' => 100
        ]);
        $this->updateFuelAtAirport->execute($airport->identifier, 10, 2, 'increment');
        $airport->refresh();
        $this->assertEquals(110, $airport->jetfuel_qty);
    }
}
