<?php

namespace Tests\Feature\Api\Tracker;

use App\Models\Aircraft;
use App\Models\Booking;
use App\Models\Enums\PirepState;
use App\Models\Fleet;
use App\Models\Flight;
use App\Models\FlightLog;
use App\Models\Pirep;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Laravel\Sanctum\Sanctum;
use Tests\TestCase;

class CancelPirepTest extends TestCase
{
    use RefreshDatabase;

    protected Model $user;
    protected Model $pirep;
    protected Model $flight;
    protected Model $fleet;
    protected Model $aircraft;
    protected Model $booking;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::factory()->create();
        $this->fleet = Fleet::factory()->create();
        $this->aircraft = Aircraft::factory()->create([
            'fleet_id' => $this->fleet->id
        ]);
        $this->flight = Flight::factory()->create();
        $this->booking = Booking::factory()->create([
            'flight_id' => $this->flight->id,
            'user_id' => $this->user->id
        ]);
        $this->pirep = Pirep::factory()->create([
            'user_id' => $this->user->id,
            'flight_id' => $this->flight->id,
            'booking_id' => $this->booking->id,
            'aircraft_id' => $this->aircraft
        ]);

        $this->booking->has_dispatch = $this->pirep->id;
        $this->booking->save();

    }
    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_pirep_is_cancelled()
    {
        Sanctum::actingAs(
            $this->user,
            ['*']
        );

        $response = $this->post('/api/pirep/reset', ['pirep_id' => $this->pirep->id]);
        $response->assertStatus(200);
        $this->assertDatabaseHas('pireps', ['id' => $this->pirep->id, 'state' => PirepState::DISPATCH]);
    }

    public function test_pirep_has_no_logs()
    {

        $log = new FlightLog();
        $log->pirep_id = $this->pirep->id;
        $log->lat = -6.36098;
        $log->lon = 143.23202;
        $log->distance = 2;
        $log->heading = 90;
        $log->altitude = 1000;
        $log->indicated_speed = 100;
        $log->ground_speed = 105;
        $log->fuel_flow = 23;
        $log->vs = 580;
        $log->sim_time = Carbon::now();
        $log->zulu_time = Carbon::createFromTimestampUTC(Carbon::now());
        $log->save();

        Sanctum::actingAs(
            $this->user,
            ['*']
        );

        $response = $this->postJson('/api/pirep/reset', ['pirep_id' => $this->pirep->id]);
        $this->assertDatabaseMissing('flight_logs', ['pirep_id' => $this->pirep->id]);
    }
}
