<?php

namespace Tests\Feature\Api\Tracker;

use App\Models\Aircraft;
use App\Models\Airport;
use App\Models\Booking;
use App\Models\Contract;
use App\Models\ContractCargo;
use App\Models\Enums\PirepState;
use App\Models\Fleet;
use App\Models\Flight;
use App\Models\FlightLog;
use App\Models\Pirep;
use App\Models\PirepCargo;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\DB;
use Laravel\Sanctum\Sanctum;
use Tests\TestCase;

class CancelPirepTest extends TestCase
{
    use RefreshDatabase;

    protected Model $user;
    protected Model $pirep;
    protected Model $flight;
    protected Model $fleet;
    protected Model $aircraft;
    protected Model $booking;
    protected Model $contract;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $aymr = Airport::factory()->create([
            'identifier' => 'AYMR'
        ]);
        $aymn = Airport::factory()->create([
            'identifier' => 'AYMN'
        ]);

        $this->user = User::factory()->create();
        $this->fleet = Fleet::factory()->create();
        $this->aircraft = Aircraft::factory()->create([
            'fleet_id' => $this->fleet->id,
            'fuel_onboard' => 50,
            'current_airport_id' => $aymr->id,
            'user_id' => $this->user->id
        ]);
        DB::table('cargo_types')->insert([
            ['type' => 1, 'text' => 'Solar Panels'],
            ['type' => 1, 'text' => 'Building materials'],
            ['type' => 2, 'text' => 'Medics'],
            ['type' => 2, 'text' => 'Locals'],
        ]);

        $this->contract = Contract::factory()->create([
            'contract_value' => 250.00,
            'dep_airport_id' => $aymr->id,
            'arr_airport_id' => $aymn->id,
        ]);

        $this->pirep = Pirep::factory()->create([
            'user_id' => $this->user->id,
            'destination_airport_id' => 'AYMN' ?? $this->contract->arr_airport_id,
            'departure_airport_id' => 'AYMR' ?? $this->contract->dep_airport_id,
            'aircraft_id' => $this->aircraft
        ]);

        $pirepCargo = PirepCargo::factory()->create([
            'pirep_id' => $this->pirep->id,
            'contract_cargo_id' => $this->contract->id
        ]);

        FlightLog::factory()->create([
            'pirep_id' => $this->pirep->id,
            'lat' => -6.36263,
            'lon' => 143.23056
        ]);

        FlightLog::factory()->create([
            'pirep_id' => $this->pirep->id,
            'lat' => -6.14477,
            'lon' => 143.65752
        ]);

    }
    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_pirep_is_cancelled()
    {
        Sanctum::actingAs(
            $this->user,
            ['*']
        );

        $response = $this->get('/api/pirep/reset');
        $response->assertStatus(200);
        $this->assertDatabaseHas('pireps', ['id' => $this->pirep->id, 'state' => PirepState::DISPATCH]);
    }

    public function test_pirep_has_no_logs()
    {

        $log = new FlightLog();
        $log->pirep_id = $this->pirep->id;
        $log->lat = -6.36098;
        $log->lon = 143.23202;
        $log->distance = 2;
        $log->heading = 90;
        $log->altitude = 1000;
        $log->indicated_speed = 100;
        $log->ground_speed = 105;
        $log->fuel_flow = 23;
        $log->vs = 580;
        $log->sim_time = Carbon::now();
        $log->zulu_time = Carbon::createFromTimestampUTC(Carbon::now());
        $log->save();

        Sanctum::actingAs(
            $this->user,
            ['*']
        );

        $response = $this->get('/api/pirep/reset');
        $this->assertDatabaseMissing('flight_logs', ['pirep_id' => $this->pirep->id]);
    }
}
