<?php

namespace Tests\Feature\Api\Tracker;

use App\Models\Aircraft;
use App\Models\Booking;
use App\Models\Fleet;
use App\Models\Flight;
use App\Models\Pirep;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Laravel\Sanctum\Sanctum;
use Tests\TestCase;

class PostFlightLogTest extends TestCase
{
    use RefreshDatabase;

    protected Model $user;
    protected Model $pirep;
    protected Model $flight;
    protected Model $fleet;
    protected Model $aircraft;
    protected Model $booking;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::factory()->create();
        $this->fleet = Fleet::factory()->create();
        $this->aircraft = Aircraft::factory()->create([
            'fleet_id' => $this->fleet->id
        ]);
        $this->flight = Flight::factory()->create();
        $this->booking = Booking::factory()->create([
            'flight_id' => $this->flight->id,
            'user_id' => $this->user->id
        ]);
        $this->pirep = Pirep::factory()->create([
            'user_id' => $this->user->id,
            'flight_id' => $this->flight->id,
            'booking_id' => $this->booking->id,
            'aircraft_id' => $this->aircraft
        ]);

        $this->booking->has_dispatch = $this->pirep->id;
        $this->booking->save();

    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_add_new_log_success()
    {
        Sanctum::actingAs(
            $this->user,
            ['*']
        );
        $data = [
            'pirep_id'=> $this->pirep->id,
            'lat' => -5.82781,
            'lon' => 144.29953,
            'distance' => 3,
            'heading' => 257,
            'altitude' => 2342,
            'indicated_speed' => 165,
            'ground_speed' => 171,
            'fuel_flow' => 12.1,
            'vs' => 345.02,
            'sim_time' => Carbon::now(),
            'zulu_time' => Carbon::createFromTimestampUTC(Carbon::now()),
        ];

        $response = $this->postJson('/api/log', $data);
        $response->assertStatus(201);
    }

    public function test_add_new_log_missing_data_fails_gracefully()
    {
        Sanctum::actingAs(
            $this->user,
            ['*']
        );
        $data = [
            'pirep_id'=> $this->pirep->id,
            'lat' => -5.82781,
            'lon' => 144.29953,
            'distance' => 3,
            'heading' => 257,
            'altitude' => 2342,
            'ground_speed' => 171,
            'fuel_flow' => 12.1,
            'vs' => 345.02,
            'sim_time' => Carbon::now(),
            'zulu_time' => Carbon::createFromTimestampUTC(Carbon::now()),
        ];

        $response = $this->postJson('/api/log', $data);
        $response->assertStatus(422);
    }
}
