<?php

namespace Tests\Unit\Services\Cargo;

use App\Services\Cargo\GenerateCargoQty;
use Tests\TestCase;

class GenerateQtyTest extends TestCase
{
    protected GenerateCargoQty $generateCargoQty;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->generateCargoQty = $this->app->make(GenerateCargoQty::class);
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_generate_qty_returns_int()
    {
        $qty = $this->generateCargoQty->execute(10);
        $this->assertIsInt($qty);
    }

    public function test_generate_qty_returns_int_lower_than_max()
    {
        $qty = $this->generateCargoQty->execute(10);
        $this->assertLessThanOrEqual(10, $qty);
    }
}
