<?php

namespace Tests\Unit\Services\Cargo;

use App\Services\CargoService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class GeneratePaxTest extends TestCase
{
    use RefreshDatabase;

    protected CargoService $cargoService;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        DB::table('cargo_types')->insert([
            ['type' => 2, 'text' => 'Medics'],
            ['type' => 2, 'text' => 'Locals'],
        ]);

        $this->cargoService = new CargoService();
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_pax_generation_returns_array()
    {
        $pax = $this->cargoService->generatePax(10);
        $this->assertIsArray($pax);
        $this->assertArrayHasKey('pax_type', $pax);
        $this->assertArrayHasKey('baggage', $pax);
    }

}
