<?php

namespace Tests\Unit\Services\User;

use App\Models\Enums\TransactionTypes;
use App\Models\User;
use App\Services\UserService;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class AddUserAccountEntryTest extends TestCase
{
    use RefreshDatabase;

    protected UserService $userService;
    protected Model $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::factory()->create();
        $this->userService = new UserService();
    }
    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_positive_entry_gets_added()
    {
        $this->userService->addUserAccountEntry($this->user->id, TransactionTypes::FlightPay, 30);
        $this->assertDatabaseHas('user_accounts', [
            'user_id' => $this->user->id,
            'type' => TransactionTypes::FlightPay,
            'total' => 30
        ]);
    }

    public function test_negative_entry_gets_added()
    {
        $this->userService->addUserAccountEntry($this->user->id, TransactionTypes::Jumpseat, -50);
        $this->assertDatabaseHas('user_accounts', [
            'user_id' => $this->user->id,
            'type' => TransactionTypes::Jumpseat,
            'total' => -50
        ]);
    }
}
