<?php

namespace Tests\Unit\Services\User;

use App\Models\User;
use App\Services\User\UpdateUserLocation;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class UpdatePilotLocationTest extends TestCase
{
    use RefreshDatabase;

    protected UpdateUserLocation $updateUserLocation;
    protected Model $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::factory()->create();
        $this->updateUserLocation = $this->app->make(UpdateUserLocation::class);
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_pilot_location_updates_correctly()
    {
        $icao = 'EGLL';
        $this->updateUserLocation->execute($icao, $this->user->id);
        $this->assertDatabaseHas('users', [
            'current_airport_id' => $icao
        ]);
    }
}
