<?php

namespace Tests\Unit\Services\User;

use App\Models\User;
use App\Services\UserService;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class UpdatePilotLocationTest extends TestCase
{
    use RefreshDatabase;

    protected UserService $userService;
    protected Model $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::factory()->create();
        $this->userService = new UserService();
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_pilot_location_updates_correctly()
    {
        $icao = 'EGLL';
        $this->userService->updatePilotLocation($icao, $this->user->id);
        $this->assertDatabaseHas('users', [
            'current_airport_id' => $icao
        ]);
    }
}
