<?php

namespace Tests\Unit\Services\Contract;

use App\Models\Contract;
use App\Models\ContractCargo;
use App\Services\Contracts\RemoveStaleContracts;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class DeleteStaleContractsTest extends TestCase
{
    use RefreshDatabase;

    protected RemoveStaleContracts $removeStaleContracts;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->removeStaleContracts = $this->app->make(RemoveStaleContracts::class);
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_stale_contracts_are_removed()
    {
        $contract = Contract::factory()->create([
            'expires_at' => Carbon::now()->subDays(5),
            'user_id' => null,
            'is_available' => true,
            'is_completed' => false
        ]);

        $this->removeStaleContracts->execute();

        $this->assertDatabaseMissing('contracts', [
            'id' => $contract->id
        ]);
    }

    public function test_stale_contracts_cargo_are_removed()
    {
        $contract = Contract::factory()->create([
            'expires_at' => Carbon::now()->subDays(5),
            'user_id' => null,
            'is_available' => true,
            'is_completed' => false
        ]);

        $cargo = ContractCargo::factory()->count(2)->create([
            'contract_id' => $contract->id
        ]);

        $this->removeStaleContracts->execute();

        $this->assertDatabaseMissing('contract_cargos', [
            'contract_id' => $contract->id
        ]);
    }

    public function test_expired_contracts_with_a_user_are_not_removed()
    {
        $contract = Contract::factory()->create([
            'expires_at' => Carbon::now()->subDays(5),
            'user_id' => 1
        ]);

        $this->removeStaleContracts->execute();

        $this->assertDatabaseHas('contracts', [
            'id' => $contract->id
        ]);
    }

    public function test_current_contracts_are_not_removed()
    {
        $contract = Contract::factory()->create([
            'expires_at' => Carbon::now()->addDays(5)
        ]);

        $this->removeStaleContracts->execute();

        $this->assertDatabaseHas('contracts', [
            'id' => $contract->id
        ]);
    }
}
