<?php

namespace Tests\Unit\Services\Contract;

use App\Models\Airport;
use App\Services\ContractService;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class GenerateHubContractsTest extends TestCase
{
    use RefreshDatabase;

    protected ContractService $contractService;
    protected Model $airport1;
    protected Model $airport2;
    protected Model $airport3;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        DB::table('cargo_types')->insert([
            ['type' => 1, 'text' => 'Solar Panels'],
            ['type' => 1, 'text' => 'Building materials'],
            ['type' => 2, 'text' => 'Medics'],
            ['type' => 2, 'text' => 'Locals'],
        ]);
        $this->airport1 = Airport::factory()->create();
        $this->airport2 = Airport::factory()->create([
            'identifier' => 'AYMH'
        ]);
        $this->airport3 = Airport::factory()->create([
            'identifier' => 'WAVG'
        ]);
        $this->contractService = new ContractService();
    }
    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_contract_to_hub_is_generated()
    {
        $this->contractService->generateHubContracts($this->airport1, 2);
        $this->assertDatabaseHas('contracts', [
            'dep_airport_id' => $this->airport1->identifier,
            'arr_airport_id' => $this->airport2->identifier
        ]);
    }
}
