<?php

namespace Tests\Unit\Services\Contract;

use App\Models\Airport;
use App\Models\Contract;
use App\Models\ContractCargo;
use App\Models\Pirep;
use App\Services\Contracts\UpdateContractCargoProgress;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class SetCargoCompleteTest extends TestCase
{
    use RefreshDatabase;

    protected UpdateContractCargoProgress $updateContractCargoProgress;
    protected Contract $contract;
    protected Pirep $pirep;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        DB::table('cargo_types')->insert([
            ['type' => 1, 'text' => 'Solar Panels'],
            ['type' => 1, 'text' => 'Building materials'],
            ['type' => 2, 'text' => 'Medics'],
            ['type' => 2, 'text' => 'Locals'],
        ]);
        $this->updateContractCargoProgress = $this->app->make(UpdateContractCargoProgress::class);

        $this->contract = Contract::factory()->create()->load('arrAirport');
        $this->pirep = Pirep::factory()->create();
    }
    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_cargo_is_completed()
    {
        $this->updateContractCargoProgress->execute($this->contract, $this->contract->arrAirport, $this->pirep);
        $this->assertDatabaseHas('contracts', [
            'id' => $this->contract->id,
            'is_completed' => true,
            'completed_pirep' => $this->pirep->id,
        ]);
    }

    public function test_cargo_is_not_completed_when_at_different_airport()
    {
        $otherAirport = Airport::factory()->create();
        $this->updateContractCargoProgress->execute($this->contract, $otherAirport, $this->pirep);
        $this->assertDatabaseHas('contracts', [
            'id' => $this->contract->id,
            'is_completed' => false,
        ]);
    }

    public function test_cargo_location_is_updated()
    {
        $otherAirport = Airport::factory()->create();
        $this->updateContractCargoProgress->execute($this->contract, $otherAirport, $this->pirep);
        $this->assertDatabaseHas('contracts', [
            'id' => $this->contract->id,
            'current_airport_id' => $otherAirport->id
        ]);
    }
}
