<?php

namespace Tests\Unit\Services\Tours;

use App\Models\Airport;
use App\Models\Pirep;
use App\Models\Tour;
use App\Models\TourCheckpointUser;
use App\Models\TourUser;
use App\Models\User;
use App\Services\Tours\CheckTourProgress;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class CheckTourProgressTest extends TestCase
{
    use RefreshDatabase;

    protected Model $tour;
    protected Model $user;
    protected Model $anotherUser;
    protected Model $tourUser;
    protected Model $anotherTourUser;
    protected Model $tourCheckpointUser;
    protected Model $tourCheckpointUser1;

    protected Model $anotherTourCheckpointUser;
    protected Model $anotherTourCheckpointUser1;

    protected Airport $aymr, $aymn, $aymh, $wavg, $ayym;

    protected Model $pirep;

    protected CheckTourProgress $checkTourProgress;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->aymr = Airport::factory()->create(['identifier' => 'AYMR']);
        $this->aymn = Airport::factory()->create(['identifier' => 'AYMN']);
        $this->aymh = Airport::factory()->create(['identifier' => 'AYMH']);
        $this->wavg = Airport::factory()->create(['identifier' => 'WAVG']);
        $this->ayym = Airport::factory()->create(['identifier' => 'AYYM']);

        $this->checkTourProgress = $this->app->make(CheckTourProgress::class);
        $this->tour = Tour::factory()->create([
            'title' => 'test',
            'description' => 'test',
            'award_id' => 1,
            'start_airport_id' => $this->aymr->id
        ]);
        $this->user = User::factory()->create();
        $this->anotherUser = User::factory()->create();

        $this->tourUser = TourUser::factory()->create([
            'user_id' => $this->user->id,
            'tour_id' => $this->tour->id,
            'next_airport_id' => $this->wavg->id
        ]);
        $this->anotherTourUser = TourUser::factory()->create([
            'user_id' => $this->anotherUser->id,
            'tour_id' => $this->tour->id,
            'next_airport_id' => $this->wavg->id
        ]);
        $this->tourCheckpointUser = TourCheckpointUser::factory()->create([
            'user_id' => $this->user->id,
            'tour_id' => $this->tour->id,
            'section' => 1,
            'checkpoint_airport_id' => $this->wavg->id
        ]);
        $this->tourCheckpointUser1 = TourCheckpointUser::factory()->create([
            'user_id' => $this->user->id,
            'tour_id' => $this->tour->id,
            'section' => 2,
            'checkpoint_airport_id' => $this->aymh->id
        ]);
        $this->anotherTourCheckpointUser = TourCheckpointUser::factory()->create([
            'user_id' => $this->anotherUser->id,
            'tour_id' => $this->tour->id,
            'section' => 1,
            'checkpoint_airport_id' => $this->wavg->id
        ]);
        $this->anotherTourCheckpointUser1 = TourCheckpointUser::factory()->create([
            'user_id' => $this->anotherUser->id,
            'tour_id' => $this->tour->id,
            'section' => 2,
            'checkpoint_airport_id' => $this->aymh->id
        ]);
        $this->pirep = Pirep::factory()->create([
            'user_id' => $this->user->id,
            'tour_id' => $this->tour->id,
            'departure_airport_id' => 'AYYM',
            'destination_airport_id' => 'WAVG',
        ]);
    }

    /**
     * A basic unit test example.
     */
    public function test_next_checkpoint_set(): void
    {
        $firstPirep = Pirep::factory()->create([
            'user_id' => $this->user->id,
            'tour_id' => $this->tour->id,
            'departure_airport_id' => 'AYMN',
            'destination_airport_id' => 'AYYM',
            'aircraft_id' => $this->pirep->aircraft_id
        ]);
        $this->checkTourProgress->execute($firstPirep);
        $this->tourUser->refresh();
        $this->assertEquals($this->wavg->id, $this->tourUser->next_airport_id);
        $this->checkTourProgress->execute($this->pirep);
        $this->tourUser->refresh();
        $this->assertEquals($this->aymh->id, $this->tourUser->next_airport_id);
        $this->assertDatabaseHas('tour_users', [
            'user_id' => $this->user->id,
            'next_airport_id' => $this->aymh->id
        ]);
    }

    public function test_nothing_happens_if_not_checkpoint(): void
    {
        $this->pirep->destination_airport_id = 'AYMN';
        $this->pirep->save();
        $this->checkTourProgress->execute($this->pirep);
        $this->tourUser->refresh();
        $this->assertEquals($this->wavg->id, $this->tourUser->next_airport_id);
    }

    public function test_checkpoint_completed(): void
    {
        $this->checkTourProgress->execute($this->pirep);
        $this->tourCheckpointUser->refresh();
        $this->assertEquals(true, $this->tourCheckpointUser->is_completed);
    }

    public function test_only_correct_user_checkpoint_completed(): void
    {
        $user = User::factory()->create();
        $other = TourCheckpointUser::factory()->create([
            'user_id' => $user->id,
            'tour_id' => $this->tour->id,
            'section' => 1,
            'checkpoint_airport_id' => $this->wavg->id
        ]);
        $other1 = TourCheckpointUser::factory()->create([
            'user_id' => $user->id,
            'tour_id' => $this->tour->id,
            'section' => 2,
            'checkpoint_airport_id' => $this->aymh->id
        ]);
        $this->checkTourProgress->execute($this->pirep);
        $other->refresh();
        $this->assertEquals(false, $other->is_completed);
    }

    public function test_progress_updated(): void
    {
        $this->checkTourProgress->execute($this->pirep);
        $this->tourUser->refresh();
        $this->assertEquals(50, $this->tourUser->progress);
    }

    public function test_correct_tour_progress_updated(): void
    {
        $tour2 = Tour::factory()->create([
            'title' => 'test',
            'description' => 'test',
            'award_id' => 1,
            'start_airport_id' => $this->aymr->id
        ]);
        $tour2User = TourUser::factory()->create([
            'user_id' => $this->user->id,
            'tour_id' => $tour2->id,
            'next_airport_id' => $this->wavg->id
        ]);
        $other = TourCheckpointUser::factory()->create([
            'user_id' => $this->user->id,
            'tour_id' => $tour2->id,
            'section' => 1,
            'checkpoint_airport_id' => $this->wavg->id
        ]);
        $other1 = TourCheckpointUser::factory()->create([
            'user_id' => $this->user->id,
            'tour_id' => $tour2->id,
            'section' => 2,
            'checkpoint_airport_id' => $this->aymh->id
        ]);
        $this->checkTourProgress->execute($this->pirep);
        $this->tourUser->refresh();
        $this->assertEquals(0, $tour2User->progress);
    }

    public function test_tour_completed(): void
    {
        $this->tourUser->next_airport_id = $this->aymh->id;
        $this->tourUser->save();
        $this->tourCheckpointUser->is_completed = true;
        $this->tourCheckpointUser->save();
        $this->pirep->destination_airport_id = 'AYMH';
        $this->pirep->save();
        $this->checkTourProgress->execute($this->pirep);
        $this->tourUser->refresh();
        $this->assertEquals(true, $this->tourUser->is_completed);
    }

    public function test_tour_award_added(): void
    {
        $this->tourUser->next_airport_id = $this->aymh->id;
        $this->tourUser->save();
        $this->tourCheckpointUser->is_completed = true;
        $this->tourCheckpointUser->save();
        $this->pirep->destination_airport_id = 'AYMH';
        $this->pirep->save();
        $this->checkTourProgress->execute($this->pirep);

        $this->assertDatabaseHas('award_user', [
            'user_id' => $this->user->id,
            'award_id' => $this->tour->award_id
        ]);
    }

    public function test_tour_without_award_does_not_break(): void
    {
        $tour2 = Tour::factory()->create([
            'title' => 'test',
            'description' => 'test',
            'start_airport_id' => $this->aymr->id,
            'award_id' => null
        ]);
        $tour2User = TourUser::factory()->create([
            'user_id' => $this->user->id,
            'tour_id' => $tour2->id,
            'next_airport_id' => $this->aymh->id
        ]);
        $other = TourCheckpointUser::factory()->create([
            'user_id' => $this->user->id,
            'tour_id' => $tour2->id,
            'section' => 1,
            'is_completed' => true,
            'checkpoint_airport_id' => $this->wavg->id
        ]);
        $other1 = TourCheckpointUser::factory()->create([
            'user_id' => $this->user->id,
            'tour_id' => $tour2->id,
            'section' => 2,
            'checkpoint_airport_id' => $this->aymh->id
        ]);
        $this->pirep->tour_id = $tour2->id;
        $this->pirep->save();
        $this->checkTourProgress->execute($this->pirep);

        $this->assertDatabaseMissing('award_user', [
            'user_id' => $this->user->id
        ]);
    }
}
