<?php

namespace Tests\Unit\Services\Dispatch;

use App\Models\Enums\WeightConsts;
use App\Services\Dispatch\CalcFuelWeight;
use Tests\TestCase;

class CalcFuelWeightTest extends TestCase
{
    protected CalcFuelWeight $calcFuelWeight;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->calcFuelWeight = app()->make(CalcFuelWeight::class);
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_fuel_weight_returned_correctly_for_avgas()
    {
        $expected = WeightConsts::AVGAS_WEIGHT * 100;
        $actual = $this->calcFuelWeight->execute(1, 100);
        $this->assertEquals($expected, $actual);
    }

    public function test_fuel_weight_returned_correctly_for_jetfuel()
    {
        $expected = WeightConsts::JET_FUEL_WEIGHT * 100;
        $actual = $this->calcFuelWeight->execute(2, 100);
        $this->assertEquals($expected, $actual);
    }
}
