<?php

namespace Tests\Unit\Services\Aircraft;

use App\Models\Aircraft;
use App\Models\AircraftEngine;
use App\Models\Enums\MaintenanceTypes;
use App\Models\Fleet;
use App\Models\User;
use App\Services\Aircraft\AddMaintenanceLog;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class AddMaintenanceLogTest extends TestCase
{
    use RefreshDatabase;
    protected AddMaintenanceLog $addMaintenanceLog;
    protected Model $user;
    protected Model $aircraft;
    protected Model $fleet;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->addMaintenanceLog = app()->make(AddMaintenanceLog::class);
        $this->fleet = Fleet::factory()->create();
        $this->aircraft = Aircraft::factory()->create([
            'fleet_id' => $this->fleet->id
        ]);
        $this->user = User::factory()->create();
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_maintenance_log_added()
    {
        $this->addMaintenanceLog->execute($this->aircraft->id, MaintenanceTypes::GeneralMaintenance, $this->user->id, 200);
        $this->assertDatabaseHas('maintenance_logs', [
            'cost' => 200,
            'aircraft_id' => $this->aircraft->id,
            'maintenance_type' => MaintenanceTypes::GeneralMaintenance
        ]);
    }

    public function test_engine_maintenance_log_added()
    {
        $engine = AircraftEngine::factory()->create([
            'aircraft_id' => $this->aircraft->id
        ]);
        $this->addMaintenanceLog->execute($this->aircraft->id, MaintenanceTypes::Maintenance100hr, $this->user->id, 200, $engine->id);
        $this->assertDatabaseHas('maintenance_logs', [
            'cost' => 200,
            'aircraft_id' => $this->aircraft->id,
            'engine_id' => $engine->id,
            'maintenance_type' => MaintenanceTypes::Maintenance100hr
        ]);
    }
}
