<?php

namespace Tests\Unit\Services\Aircraft;

use App\Models\Aircraft;
use App\Models\AircraftEngine;
use App\Models\Fleet;
use App\Services\Aircraft\CheckAircraftMaintenanceStatus;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class CheckAircraftMaintenanceStatusTest extends TestCase
{
    use RefreshDatabase;

    protected CheckAircraftMaintenanceStatus $checkAircraftMaintenanceStatus;
    protected Model $aircraft1;
    protected Model $aircraft1Engine;
    protected Model $aircraft2;
    protected Model $aircraft2Engine;
    protected Model $fleet;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->fleet = Fleet::factory()->create([
            'tbo_mins' => 100
        ]);

        $this->aircraft1 = Aircraft::factory()->create([
            'fleet_id' => $this->fleet->id,
            'mins_since_100hr' => 6000
        ]);

        $this->aircraft1Engine = AircraftEngine::factory()->create([
            'aircraft_id' => $this->aircraft1->id,
            'engine_no' => 1,
            'mins_since_tbo' => 6000
        ]);

        $this->aircraft2 = Aircraft::factory()->create([
            'registration' => 'P2-TEST',
            'fleet_id' => $this->fleet->id,
            'mins_since_100hr' => 10
        ]);

        $this->aircraft2Engine = AircraftEngine::factory()->create([
            'aircraft_id' => $this->aircraft2->id,
            'engine_no' => 1,
            'mins_since_tbo' => 10
        ]);

        $this->checkAircraftMaintenanceStatus = $this->app->make(CheckAircraftMaintenanceStatus::class);
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_aircraft_maintence_is_needed()
    {
        $res = $this->checkAircraftMaintenanceStatus->execute($this->aircraft1->id);
        $this->assertTrue($res);
    }

    public function test_aircraft_maintence_is_not_needed()
    {
        $res = $this->checkAircraftMaintenanceStatus->execute($this->aircraft2->id);
        $this->assertFalse($res);
    }
}
