<?php

namespace Tests\Unit\Services\Aircraft;

use App\Models\Aircraft;
use App\Models\Airport;
use App\Models\Contract;
use App\Models\Enums\AircraftState;
use App\Models\Fleet;
use App\Models\Pirep;
use App\Models\PirepCargo;
use App\Models\User;
use App\Services\Aircraft\UpdateAircraftAfterFlight;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class UpdateAircraftDataTest extends TestCase
{
    use RefreshDatabase;

    protected User $user;
    protected Pirep $pirep;
    protected PirepCargo $pirepCargo;
    protected Contract $contract;
    protected PirepCargo $contractCargo;
    protected Fleet $fleet;
    protected Aircraft $aircraft;
    protected Airport $aymr;
    protected Airport $aymn;
    protected UpdateAircraftAfterFlight $updateAircraftAfterFlight;


    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->aymn = Airport::factory()->create([
            'identifier' => 'AYMN',
            'lat' => -5.20708,
            'lon' => 144.78500
        ]);

        $this->aymr = Airport::factory()->create([
            'identifier' => 'AYMR',
            'lat' => -6.36188,
            'lon' => 143.23070
        ]);

        $this->user = User::factory()->create([
            'rank_id' => 1,
            'flights_time' => 299,
            'points' => 49,
            'created_at' => Carbon::now()->addYears(-2)
        ]);
        $this->fleet = Fleet::factory()->create();
        $this->aircraft = Aircraft::factory()->create([
            'fleet_id' => $this->fleet->id,
            'fuel_onboard' => 50,
            'current_airport_id' => $this->aymr->id,
            'user_id' => $this->user->id
        ]);
        DB::table('cargo_types')->insert([
            ['type' => 1, 'text' => 'Solar Panels'],
            ['type' => 1, 'text' => 'Building materials'],
            ['type' => 2, 'text' => 'Medics'],
            ['type' => 2, 'text' => 'Locals'],
        ]);

        $this->contract = Contract::factory()->create([
            'contract_value' => 250.00,
            'dep_airport_id' => $this->aymr->id,
            'arr_airport_id' => $this->aymn->id,
        ]);

        $this->pirep = Pirep::factory()->create([
            'user_id' => $this->user->id,
            'arrival_airport_id' => $this->contract->arr_airport_id,
            'departure_airport_id' => $this->contract->dep_airport_id,
            'aircraft_id' => $this->aircraft
        ]);

        $this->pirepCargo = PirepCargo::factory()->create([
            'pirep_id' => $this->pirep->id,
            'contract_cargo_id' => $this->contract->id
        ]);

        $this->updateAircraftAfterFlight = $this->app->make(UpdateAircraftAfterFlight::class);
    }
    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_aircraft_state_reset()
    {
        $this->aircraft->state = AircraftState::IN_USE;
        $this->updateAircraftAfterFlight->execute($this->aircraft, $this->pirep);
        $this->assertDatabaseHas('aircraft', [
            'id' => $this->aircraft->id,
            'state' => AircraftState::AVAILABLE
        ]);
    }

    public function test_aircraft_fuel_updated()
    {
        $this->pirep->fuel_used = 20;
        $this->aircraft->fuel_onboard = 50;
        $this->updateAircraftAfterFlight->execute($this->aircraft, $this->pirep);
        $this->assertDatabaseHas('aircraft', [
            'id' => $this->aircraft->id,
            'fuel_onboard' => 30
        ]);
    }

    public function test_aircraft_fuel_remains_0_when_0_fuel()
    {
        $aircraft = Aircraft::factory()->create([
            'fleet_id' => $this->fleet->id,
            'fuel_onboard' => 0,
            'registration' => 'N12345'
        ]);
        $this->pirep->fuel_used = 20;
        $this->updateAircraftAfterFlight->execute($aircraft, $this->pirep);
        $this->assertDatabaseHas('aircraft', [
            'id' => $aircraft->id,
            'fuel_onboard' => 0
        ]);
    }

    public function test_aircraft_hours_updated()
    {
        $this->pirep->flight_time = 20;
        $this->aircraft->flight_time_mins = 100;
        $this->updateAircraftAfterFlight->execute($this->aircraft, $this->pirep);
        $this->assertDatabaseHas('aircraft', [
            'id' => $this->aircraft->id,
            'flight_time_mins' => 120
        ]);
    }

    public function test_aircraft_location_updated()
    {
        $icao = Airport::factory()->create(['identifier' => 'EGLL']);
        $lat = -6.14617;
        $lon = 143.65733;
        $this->pirep->arrAirport = $icao;
        $this->pirep->current_lat = $lat;
        $this->pirep->current_lon = $lon;
        $this->updateAircraftAfterFlight->execute($this->aircraft, $this->pirep);
        $this->assertDatabaseHas('aircraft', [
            'id' => $this->aircraft->id,
            'current_airport_id' => $icao->id,
            'last_lat' => $lat,
            'last_lon' => $lon
        ]);
    }

    public function test_aircraft_last_flight_updated()
    {
        $date = Carbon::now();
        $this->pirep->submitted_at = $date;
        $this->updateAircraftAfterFlight->execute($this->aircraft, $this->pirep);
        $this->assertDatabaseHas('aircraft', [
            'id' => $this->aircraft->id,
            'last_flight' => $date
        ]);
    }

}
