<?php

namespace Tests\Unit\Finance;

use App\Models\Enums\TransactionTypes;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class GetUserBalanceTest extends TestCase
{
    use RefreshDatabase;

    protected User $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::factory()->create();
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_get_user_balance_returns_zero_when_nothing(): void
    {
        $total = $this->user->balance;
        $this->assertEquals(0, $total);
    }

    public function test_get_user_balance_returns_correct_value(): void
    {
        DB::table('user_accounts')->insert([
            ['user_id' => $this->user->id, 'type' => TransactionTypes::Jumpseat, 'total' => -250],
            ['user_id' => $this->user->id, 'type' => TransactionTypes::Bonus, 'total' => 800]
        ]);

        $total = $this->user->balance;
        $this->assertEquals(800-250, $total);
    }
}
