name: Bushdivers Pre-Deploy

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Run Tests
    uses: ./.github/workflows/test-framework.yml

  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    needs: [ run-tests ]
    env:
      CLONE_URL: ${{ secrets.CLONE_URL }}
      DEPLOY_EMAIL: ${{ secrets.DEPLOY_EMAIL }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
    steps:
      - name: Post Webhook
        if: ${{ env.CLONE_URL != '' }}
        run: |
          curl -d '{"payload": {"clone_url": "${{env.CLONE_URL}}", "branch": "main", "new_ref": "latest", "email": "${{env.DEPLOY_EMAIL}}"}}' -H "Content-Type: application/json" -X POST "${{ env.WEBHOOK_URL }}"



