name: Bushdivers PR

on:
  pull_request:
    branches:
      - '**'

env:
  LARAVEL_BYPASS_ENV_CHECK: 1

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: bushdivers_ci
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_HOST: 127.0.0.1
      DB_PORT: 3257
      MARIADB_ALLOW_EMPTY_PASSWORD: false
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: bushdivers_ci
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3257:3306
        env:
          MARIADB_ALLOW_EMPTY_PASSWORD: false
          MARIADB_ROOT_PASSWORD: password
          MARIADB_DATABASE: bushdivers_ci
        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install --ignore-platform-reqs
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Clear Config
        run: php artisan config:clear
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit

  front-end-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '20.11'
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm i
      - name: Eslint
        run: npm run lint
      - name: Check it builds
        run: npm run build
