name: Laravel Framework Test
on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: bushdivers_ci
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_PORT: 3257
      APP_ENV: testing

    services:
      mariadb:
        image: mariadb:10.6
        ports:
          - 3257:3306
        env:
          MARIADB_ALLOW_EMPTY_PASSWORD: false
          MARIADB_ROOT_PASSWORD: password
          MARIADB_DATABASE: bushdivers_ci
        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer Dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Copy .env
        run: cp .env.example .env

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-scripts
          npm ci
          npm run lint
          npm run build

      - name: Prepare application
        run: |
          php artisan config:clear
          php artisan key:generate --force
          php artisan about --only=environment

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run tests
        run: php artisan test